export const damageMock = {
  // customerFirstName: "Jason",
  // customerLastName: "Miller",
  // customerEmail: "jasonmiller@email.com",
  // customerPhone: "+497686773245",
  // customerStreet: "Longzins street 876",
  // customerCountry: "Deutschland",
  // customerCity: "Berlin",
  // customerPostalCode: "87690",
  // customerVehicleLicensePlate: "GL BG5055",
  // customerVehicleVINNumber: "1FMCU14T6JU400773",
  // tortfeasorFirstName: "Thomas",
  // tortfeasorLastName: "Muller",
  // tortfeasorEmail: "thomasmu@email.com",
  // tortfeasorPhone: "+491567898765",
  // tortfeasorStreet: "Beautiful street 87",
  // tortfeasorCountry: "Deutschland",
  // tortfeasorCity: "Munich",
  // tortfeasorPostalCode: "56789",
  // tortfeasorVehicleLicensePlate: "GL BG9876"
  customerFirstName: "",
  customerLastName: "",
  customerEmail: "",
  customerPhone: "",
  customerStreet: "",
  customerCountry: "Deutschland",
  customerCity: "",
  customerPostalCode: "",
  customerVehicleLicensePlate: "",
  customerVehicleVINNumber: "",
  tortfeasorFirstName: "",
  tortfeasorLastName: "",
  tortfeasorEmail: "",
  tortfeasorPhone: "",
  tortfeasorStreet: "",
  tortfeasorCountry: "",
  tortfeasorCity: "",
  tortfeasorPostalCode: "",
  tortfeasorVehicleLicensePlate: ""
}
