import * as Joi from "@hapi/joi";
import "joi-extract-type";

export const calculationDataModel = Joi.object({
  "calculationId": Joi.string().optional(),
  "calculationType": Joi.string().required(),
  "transferCost": Joi.number().required(),
  "mechanicsHourlyRate": Joi.number().required(),
  "electricsHourlyRate": Joi.number().required(),
  "bodyworkHourlyRate": Joi.number().required(),
  "paintHourlyRate": Joi.number().required(),
  "paintingMaterialCost": Joi.number().required(),
  "sparePartSurcharge": Joi.number().required(),
  "smallPartSurchargeIndication": Joi.string().required(),
  "smallPartSurcharge": Joi.number().required(),
});

export const CostEstimationModel = Joi.object({
  "costEstimationId": Joi.string().optional(),
  "workshopId": Joi.string().required(),
  "vehicleData": Joi.object({
    "customerVehicleLicensePlate": Joi.string().required(),
    "customerVehicleVINNumber": Joi.string().required(),
    "customerVehicleBrand": Joi.string().required(),
    "customerVehicleModel": Joi.string().required(),
    "customerVehicleFirstRegistration": Joi.date().allow(null, ""),
    "customerType": Joi.string().allow(""),
    "customerFirstName": Joi.string().required(),
    "customerLastName": Joi.string().required(),
    "customerStreet": Joi.string().allow(""),
    "customerCity": Joi.string().allow(""),
    "customerPostalCode": Joi.string().allow(""),
  }),
  "frontImages": Joi.array().empty(),
  "frontAngledLeftImages": Joi.array(),
  "frontDriverImages": Joi.array(),
  "rearAngledDriverImages": Joi.array(),
  "rearFrontImages": Joi.array(),
  "rearAngledPassengerImages": Joi.array(),
  "frontPassengerImages": Joi.array(),
  "frontRightAngledImages": Joi.array(),
  "roofImages": Joi.array(),
  "carBelowImages": Joi.array(),
  "damageFarImages": Joi.array(),
  "damageNearImages": Joi.array(),
  "damageAdditionalImages": Joi.array(),
  "speedometerImages": Joi.array(),
  "interiorImages": Joi.array(),
  "miscellaneousImages": Joi.array(),
  "calculationType": Joi.string().required(),
  "preferenceType": Joi.string().required(),
  "transferCost": Joi.number().required(),
  "mechanicsHourlyRate": Joi.number().required(),
  "electricsHourlyRate": Joi.number().required(),
  "bodyworkHourlyRate": Joi.number().required(),
  "paintHourlyRate": Joi.number().required(),
  "paintingMaterialCost": Joi.number().required(),
  "sparePartSurcharge": Joi.number().required(),
  "smallPartSurchargeIndication": Joi.string().required(),
  "smallPartSurcharge": Joi.number().required(),
  "general": Joi.string().required(),
  "bodywork": Joi.string().required(),
  "paint": Joi.string().required(),
  "interior": Joi.string().required(),
  "repairedPreviousDamage": Joi.number().required(),
  "existingOldDamage": Joi.number().required(),
  "disassembled": Joi.boolean(),
  "roadworthy": Joi.boolean(),
  "roadSafe": Joi.boolean(),
  "remarks": Joi.string().allow(""),
  "repairInstructions": Joi.string().required(),
  "reportFiles": Joi.array(),
  "otherFiles": Joi.array(),
});

export type ISetCalculationDataModel = Joi.extractType<typeof calculationDataModel>;
export type ICostEstimationModel = Joi.extractType<typeof CostEstimationModel>;
