import * as Joi from "@hapi/joi";
import "joi-extract-type";

export const UsedCarModel = Joi.object({
  "usedCarId": Joi.string().optional(),
  "workshopId": Joi.string().required(),
  "vehicleData": Joi.object({
    "customerVehicleLicensePlate": Joi.string().required(),
    "customerVehicleVINNumber": Joi.string().required(),
    "customerVehicleBrand": Joi.string().required(),
    "customerVehicleModel": Joi.string().required(),
    "customerVehicleFirstRegistration": Joi.date().allow(null, ""),
    "customerType": Joi.string().allow(""),
    "customerFirstName": Joi.string().required(),
    "customerLastName": Joi.string().required(),
    "customerStreet": Joi.string().allow(""),
    "customerCity": Joi.string().allow(""),
    "customerPostalCode": Joi.string().allow(""),
  }),
  "frontImages": Joi.array().empty(),
  "frontAngledLeftImages": Joi.array(),
  "frontDriverImages": Joi.array(),
  "rearAngledDriverImages": Joi.array(),
  "rearFrontImages": Joi.array(),
  "rearAngledPassengerImages": Joi.array(),
  "frontPassengerImages": Joi.array(),
  "frontRightAngledImages": Joi.array(),
  "roofImages": Joi.array(),
  "carBelowImages": Joi.array(),
  "damageFarImages": Joi.array(),
  "damageNearImages": Joi.array(),
  "damageAdditionalImages": Joi.array(),
  "speedometerImages": Joi.array(),
  "interiorImages": Joi.array(),
  "miscellaneousImages": Joi.array(),
  "vehicleCondition": Joi.object({
    "general": Joi.string().required(),
    "bodywork": Joi.string().required(),
    "paint": Joi.string().required(),
    "interior": Joi.string().required(),
    "repairedPreviousDamage": Joi.number().required(),
    "existingOldDamage": Joi.number().required(),
    "disassembled": Joi.boolean(),
    "roadworthy": Joi.boolean(),
    "roadSafe": Joi.boolean(),
  }),
  "aboutVehicle": Joi.object({
    "numberOfOwners": Joi.number().required(),
    "isHistoryMaintained": Joi.boolean(),
    "lastServiceDate": Joi.date().allow(null, ""),
    "vehicleKeyCount": Joi.number().required(),
    "vehicleFactor": Joi.number().required(),
    "mileage": Joi.number().required(),
    "isImported": Joi.boolean(),
    "importCountry": Joi.string().allow(""),
    "isAccidentFree": Joi.number(),
    "isDocAvailable": Joi.boolean(),
    "damageCost": Joi.number().default(0),
    "isTUVDue": Joi.boolean(),
    "tuvDueDate": Joi.date().allow(null, ""),
  }),
  "remarks": Joi.string().allow(""),
  "repairInstructions": Joi.string().required(),
  "reportFiles": Joi.array(),
  "otherFiles": Joi.array(),
});

export type IUsedCarModelModel = Joi.extractType<typeof UsedCarModel>;
